### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by JwallsRBLX** [Erizur/FNF-DaveEngine#45] opened 2023-03-21 02:05 UTC
source/PlayState.hx:303: characters 12-24 : Type not found : VideoHandler
source/Character.hx:14: lines 14-770 : ... Defined in this class
source/Note.hx:273: characters 18-28 : Class<PlayState> has no field scrollType

Im using the git version but its not working

**Comment by MemeHovy** [comment] 2023-03-21 02:21
duplicate of https://github.com/Erizur/FNF-DaveEngine/issues/43

**Comment by JwallsRBLX** [comment] 2023-03-21 02:23
This isn’t a duplicate I followed everything but it’s still not working

**Comment by MemeHovy** [comment] 2023-03-21 02:35
> This isn’t a duplicate I followed everything but it’s still not working

it is a duplicate since it's the same error, it's because I stupidly removed an import

**Comment by JwallsRBLX** [comment] 2023-03-21 02:38
Can u put it back or other people are gonna ask why isn’t it working?

**Comment by MemeHovy** [comment] 2023-03-21 02:42
I already made a PR for it https://github.com/Erizur/FNF-DaveEngine/pull/44

**Comment by JwallsRBLX** [comment] 2023-03-21 03:18
thanks but now it saying Error: Could not find haxelib "hscript-improved", does it need to be installed?

**Comment by MemeHovy** [comment] 2023-03-21 03:19
`haxelib git hscript-improved https://github.com/YoshiCrafter29/hscript-improved`

**Comment by JwallsRBLX** [comment] 2023-03-22 02:44
thanks also what the issue with the song crashing when it gets to the middle of the song

**Comment by MemeHovy** [comment] 2023-03-22 02:48
I don't know that's beyond me

**Comment by JwallsRBLX** [comment] 2023-03-22 02:53
o well at least can u help me with this when i add the new playstate.hx it says
source/HScriptTool.hx:113: characters 11-23 : hscript.Interp has no field errorHandler
source/HScriptTool.hx:147: characters 36-40 : String has no field trim
source/HScriptTool.hx:181: characters 28-46 : { r : Dynamic, depth : Int } has extra field depth
source/HScriptTool.hx:181: characters 28-46 : ... For function argument 'value'
source/HScriptTool.hx:59: characters 25-32 : String has no field replace

**Comment by JwallsRBLX** [comment] 2023-03-22 03:08
ok nvm its saying
source/PlayState.hx:7: characters 1-27 : HScriptTool has no field or subtype Script
source/PlayState.hx:511: characters 27-37 : Class<Paths> has no field scriptFile
source/PlayState.hx:512: characters 30-36 : Class<HScriptTool> has no field create
source/PlayState.hx:512: characters 43-53 : Class<Paths> has no field scriptFile

**Comment by MemeHovy** [comment] 2023-03-22 03:11
hmm, well what did you do with the code?

**Comment by JwallsRBLX** [comment] 2023-03-22 03:12
i didnt do anything i downloaded the Alpha 0.1 release i fixed the video handler than it gave me the issue

**Comment by MemeHovy** [comment] 2023-03-22 03:25
well

**Comment by MemeHovy** [comment] 2023-03-22 03:26
it compiles fine for me, here try this
```haxe
#if (hxCodec == "2.6.0") import VideoHandler;
#elseif (hxCodec >= "2.6.1") import hxcodec.VideoHandler;
#else import vlc.MP4Handler as VideoHandler;
#end
```

**Comment by JwallsRBLX** [comment] 2023-03-22 03:44
IT WORKS EEE thank u so much for the help

**Comment by MemeHovy** [comment] 2023-03-22 03:44
you're welcome bud

**Comment by Bamber126** [comment] 2023-04-02 19:32
> it compiles fine for me, here try this
> 
> ```hx
> #if hxCodec
> #if (hxCodec == "2.6.0") import VideoHandler;
> #elseif (hxCodec >= "2.6.1") import hxcodec.VideoHandler;
> #else import vlc.MP4Handler as VideoHandler;
> #end
> #end
> ```

Question
Do I put this in the project xml file?

**Closed** 2023-04-02 19:33 UTC
Labels: bug

**Comment by MemeHovy** [comment] 2023-04-02 19:44
> > it compiles fine for me, here try this
> > ```hx
> > #if hxCodec
> > #if (hxCodec == "2.6.0") import VideoHandler;
> > #elseif (hxCodec >= "2.6.1") import hxcodec.VideoHandler;
> > #else import vlc.MP4Handler as VideoHandler;
> > #end
> > #end
> > ```
> 
> Question Do I put this in the project xml file?

no you don't you fucking idiot, you put it in playstate

**Comment by Bamber126** [comment] 2023-04-02 20:10
I forgot to write back saying never mind
My bad

**Comment by MemeHovy** [comment] 2023-04-03 00:44
it's fine
